FROM node:4-slim

COPY package.json gulpfile.babel.js .babelrc /tmp/ippm/
COPY src/ippm-adder.js /tmp/ippm/src/
COPY packages/ippm-adder /usr/src/app

RUN { set -ex; \
	npm install -g npm@3; \

	# build
	cd /tmp/ippm; \
	npm install; \
	node_modules/.bin/gulp build-ippm-adder; \

	# install
	mv packages/ippm-adder/ippm-adder.js /usr/src/app; \
	cd /usr/src/app; \
	npm install; \

	mkdir /data; \
	ln -s /data/ippm-adder /usr/src/app/ws; \

	# clean up
	npm cache clean; \
	rm -r /tmp/*; \
}

WORKDIR /usr/src/app

CMD ["node", "ippm-adder.js"]
